version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://felipe:1234@db:5432/kenzie
      - SECRET_KEY=7792125bbce085d0b54cd64a7065aef4
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kenzie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U felipe -d kenzie"]
      interval: 7s
      timeout: 4s
      retries: 5
      start_period: 5s
